/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// GetProductBookResponse struct for GetProductBookResponse
type GetProductBookResponse struct {
	PriceBook *PriceBook `json:"pricebook,omitempty"`
}

// NewGetProductBookResponse instantiates a new GetProductBookResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProductBookResponse() *GetProductBookResponse {
	this := GetProductBookResponse{}
	return &this
}

// NewGetProductBookResponseWithDefaults instantiates a new GetProductBookResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProductBookResponseWithDefaults() *GetProductBookResponse {
	this := GetProductBookResponse{}
	return &this
}
// GetPriceBook returns the PriceBook field value if set, zero value otherwise.
func (o *GetProductBookResponse) GetPriceBook() PriceBook {
	if o == nil || isNil(o.PriceBook) {
		var ret PriceBook
		return ret
	}
	return *o.PriceBook
}

// GetPriceBookOk returns a tuple with the PriceBook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProductBookResponse) GetPriceBookOk() (*PriceBook, bool) {
	if o == nil || isNil(o.PriceBook) {
    return nil, false
	}
	return o.PriceBook, true
}

// HasPriceBook returns a boolean if a field has been set.
func (o *GetProductBookResponse) HasPriceBook() bool {
	if o != nil && !isNil(o.PriceBook) {
		return true
	}

	return false
}

// SetPriceBook gets a reference to the given PriceBook and assigns it to the PriceBook field.
func (o *GetProductBookResponse) SetPriceBook(v PriceBook) {
	o.PriceBook = &v
}

func (o GetProductBookResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PriceBook) {
		toSerialize["asks"] = o.PriceBook
	}
	return json.Marshal(toSerialize)
}

type NullableGetProductBookResponse struct {
	value *GetProductBookResponse
	isSet bool
}

func (v NullableGetProductBookResponse) Get() *GetProductBookResponse {
	return v.value
}

func (v *NullableGetProductBookResponse) Set(val *GetProductBookResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProductBookResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProductBookResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProductBookResponse(val *GetProductBookResponse) *NullableGetProductBookResponse {
	return &NullableGetProductBookResponse{value: val, isSet: true}
}

func (v NullableGetProductBookResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProductBookResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


