/*
Coinbase Advanced Trading API

OpenAPI 3.x specification for Coinbase Adavanced Trading

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

type CandleStick struct{
	Start *string `json:"start,omitempty"`
	Low *string `json:"low,omitempty"`
	High *string `json:"high,omitempty"`
	Open *string `json:"open,omitempty"`
	Close *string `json:"close,omitempty"`
	Volume *string `json:"volume,omitempty"`
}

// ListOrdersResponse struct for ListOrdersResponse
type ListProductsCandlestickResponse struct {
	CandleSticks  []CandleStick `json:"candles,omitempty"`
	Sequence *int32 `json:"sequence,omitempty,string"`
	HasNext *bool `json:"has_next,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
}

// NewListOrdersResponse instantiates a new ListOrdersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProductsCandlestickResponse() *ListProductsCandlestickResponse {
	this := ListProductsCandlestickResponse{}
	return &this
}

// NewListOrdersResponseWithDefaults instantiates a new ListOrdersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProductsCandlestickResponseWithDefaults() *ListProductsCandlestickResponse {
	this := ListProductsCandlestickResponse{}
	return &this
}

// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *ListProductsCandlestickResponse) GetCandleSticks() []CandleStick {
	if o == nil || isNil(o.CandleSticks) {
		var ret []CandleStick
		return ret
	}
	return o.CandleSticks
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsCandlestickResponse) GetCandleSticksOk() ([]CandleStick, bool) {
	if o == nil || isNil(o.CandleSticks) {
    return nil, false
	}
	return o.CandleSticks, true
}

// HasOrders returns a boolean if a field has been set.
func (o *ListProductsCandlestickResponse) HasCandleSticks() bool {
	if o != nil && !isNil(o.CandleSticks) {
		return true
	}

	return false
}

// SetOrders gets a reference to the given []Order and assigns it to the Orders field.
func (o *ListProductsCandlestickResponse) SetCandleSticks(v []CandleStick) {
	o.CandleSticks = v
}

// GetSequence returns the Sequence field value if set, zero value otherwise.
func (o *ListProductsCandlestickResponse) GetSequence() int32 {
	if o == nil || isNil(o.Sequence) {
		var ret int32
		return ret
	}
	return *o.Sequence
}

// GetSequenceOk returns a tuple with the Sequence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsCandlestickResponse) GetSequenceOk() (*int32, bool) {
	if o == nil || isNil(o.Sequence) {
    return nil, false
	}
	return o.Sequence, true
}

// HasSequence returns a boolean if a field has been set.
func (o *ListProductsCandlestickResponse) HasSequence() bool {
	if o != nil && !isNil(o.Sequence) {
		return true
	}

	return false
}

// SetSequence gets a reference to the given int32 and assigns it to the Sequence field.
func (o *ListProductsCandlestickResponse) SetSequence(v int32) {
	o.Sequence = &v
}

// GetHasNext returns the HasNext field value if set, zero value otherwise.
func (o *ListProductsCandlestickResponse) GetHasNext() bool {
	if o == nil || isNil(o.HasNext) {
		var ret bool
		return ret
	}
	return *o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsCandlestickResponse) GetHasNextOk() (*bool, bool) {
	if o == nil || isNil(o.HasNext) {
    return nil, false
	}
	return o.HasNext, true
}

// HasHasNext returns a boolean if a field has been set.
func (o *ListProductsCandlestickResponse) HasHasNext() bool {
	if o != nil && !isNil(o.HasNext) {
		return true
	}

	return false
}

// SetHasNext gets a reference to the given bool and assigns it to the HasNext field.
func (o *ListProductsCandlestickResponse) SetHasNext(v bool) {
	o.HasNext = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *ListProductsCandlestickResponse) GetCursor() string {
	if o == nil || isNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsCandlestickResponse) GetCursorOk() (*string, bool) {
	if o == nil || isNil(o.Cursor) {
    return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *ListProductsCandlestickResponse) HasCursor() bool {
	if o != nil && !isNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *ListProductsCandlestickResponse) SetCursor(v string) {
	o.Cursor = &v
}

func (o ListProductsCandlestickResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CandleSticks) {
		toSerialize["candles"] = o.CandleSticks
	}
	if !isNil(o.Sequence) {
		toSerialize["sequence"] = o.Sequence
	}
	if !isNil(o.HasNext) {
		toSerialize["has_next"] = o.HasNext
	}
	if !isNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return json.Marshal(toSerialize)
}

type NullableListProductsCandlestickResponse struct {
	value *ListProductsCandlestickResponse
	isSet bool
}

func (v NullableListProductsCandlestickResponse) Get() *ListProductsCandlestickResponse {
	return v.value
}

func (v *NullableListProductsCandlestickResponse) Set(val *ListProductsCandlestickResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListProductsCandlestickResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListProductsCandlestickResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProductsCandlestickResponse(val *ListProductsCandlestickResponse) *NullableListProductsCandlestickResponse {
	return &NullableListProductsCandlestickResponse{value: val, isSet: true}
}

func (v NullableListProductsCandlestickResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProductsCandlestickResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


